#!/usr/bin/env python

import sys
from optparse import OptionParser

parser = OptionParser(usage="usage: %prog")
(options, args) = parser.parse_args(sys.argv)


import clusto.scripthelpers

config, logger = clusto.scripthelpers.initScript()

from clusto import *

def main(argv):
    (opts, args) = parseargs(argv)

    try:
        clusto_node = clusto.getByName(args[0])
    except LookupError:
        return 1

    fai_classes = clusto_node.attrValues(key='fai',
                                         subkey='class',
                                         mergeContainerAttrs=True,
                                         )
    for i in fai_classes:
        print i,

    print
    return 0

def parseargs(argv):
    usage = "usage: %prog node-name"
    parser = OptionParser(usage=usage)

    (opts, args) = parser.parse_args(argv)

    if len(args) != 1:
        parser.error("Incorrect number of arguments!")
    return (opts, args)

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
