#!/usr/bin/env python
from clusto.scripthelpers import init_script
import clusto
import yaml

import sys

def main():
    if len(sys.argv) < 2:
        return -1

    servername = sys.argv[1]
    try:
        server = clusto.get_by_name(servername)
    except LookupError:
        return -1

    result = {
        'classes': ['site::base-node'],
    }
    for attr in server.attrs(key='puppet', merge_container_attrs=True):
        if attr.subkey == 'class':
            val = str(attr.value)
            if not val in result['classes']:
                result['classes'].append(val)
            continue

        if attr.subkey == 'environment':
            result['environment'] = str(attr.value)
            continue

        if not 'parameters' in result:
            result['parameters'] = {}

        if isinstance(attr.value, int) or attr.value.isdigit():
            val = int(attr.value)
        else:
            val = str(attr.value)

        subkey = str(attr.subkey)
        if not subkey in result['parameters']:
            result['parameters'][subkey] = val

    if not [x for x in result.values() if x]:
        return -1

    yaml.dump(result, sys.stdout, default_flow_style=False, explicit_start=True, indent=2)

if __name__ == '__main__':
    init_script()
    sys.exit(main())
