#!/usr/bin/env python
from clusto.scripthelpers import init_script
from clusto.drivers import BasicServer, EC2Region, EC2Zone, Pool
from clusto.services.config import conf
import clusto

import kombu

from traceback import format_exc
from pprint import pprint

QUEUE_HOST = conf('barker.hostname')
QUEUE_EXCHANGE = conf('barker.exchange')
QUEUE_NAME = conf('barker.queue')
QUEUE_VHOST = conf('barker.vhost')
QUEUE_USER = conf('barker.user')
QUEUE_PASSWORD = conf('barker.password')

EC2_SUBKEYS = {
    'ami-id': 'ami',
    'kernel-id': 'kernel',
    'instance-type': 'type',
}

def barker_callback(body, message):
    #body = json.loads(body)
    #print '-' * 80
    #pprint(body)

    if not 'ec2' in body:
        return
    if not 'instance-id' in body['ec2']:
        return
    ec2 = body['ec2']
    print ec2['instance-id']

    try:
        clusto.begin_transaction()
        server = clusto.get_or_create(ec2['instance-id'], BasicServer)

        zone = clusto.get_by_name(ec2['placement'])
        if not server in zone:
            zone.insert(server)

        server.del_attrs(key='ec2')

        for key, subkey in EC2_SUBKEYS.items():
            server.add_attr(key='ec2', subkey=subkey, value=ec2[key])

        for group in ec2['security-groups']:
            server.add_attr(key='ec2', subkey='security-group', value=group)
            if group.find('_') != -1:
                environment, role = group.lower().split('_', 1)
                p = clusto.get_or_create(environment, Pool)
                if not server in p:
                    p.insert(server)
                p = clusto.get_or_create(role, Pool)
                if not server in p:
                    p.insert(server)

        server.bind_ip_to_osport(ec2['local-ipv4'], 'nic-eth', 0)
        server.bind_ip_to_osport(ec2['public-ipv4'], 'nic-eth', 0)
        
        system = body['os']
        server.set_attr(key='system', subkey='memory',
                        value=int(system['memory']['MemTotal']) / 1024)
        server.set_attr(key='system', subkey='hostname',
                        value=system['hostname'])

        server.del_attrs(key='disk')
        blockmap = [(v.replace('/dev/', ''), k) for k, v in ec2['block-device-mapping'].items() if k != 'root']
        blockmap = dict(blockmap)
        total_disk = 0
        for i, disk in enumerate(system['disks']):
            for subkey in disk.keys():
                server.add_attr(key='disk', subkey=subkey, number=i, value=str(disk[subkey]))
            if disk['osname'] in blockmap:
                server.add_attr(key='disk', subkey='ec2-type', number=i, value=blockmap[disk['osname']])
            total_disk += disk['size']
        total_disk = total_disk / 1073741824
        server.set_attr(key='system', subkey='disk', value=total_disk)

        clusto.commit()
        message.ack()
    except:
        print format_exc()
        clusto.rollback_transaction()
    #pprint(body)

def main():
    init_script()

    exchange = kombu.Exchange(QUEUE_EXCHANGE, type='fanout')
    queue = kombu.Queue(QUEUE_NAME, exchange)
    connection = kombu.BrokerConnection(
        hostname=QUEUE_HOST,
        userid=QUEUE_USER,
        password=QUEUE_PASSWORD,
        virtual_host=QUEUE_VHOST)
    channel = connection.channel()
    consumer = kombu.Consumer(channel, queue, callbacks=[
        barker_callback
    ])
    consumer.consume()
    while True:
        connection.drain_events()

if __name__ == '__main__':
	main()
