#!/usr/bin/env python
from clusto import scripthelpers
from clusto.services import dhcp

if __name__ == '__main__':
    scripthelpers.init_script()
    server = dhcp.ClustoDHCPServer()
    server.run()
