#!/usr/bin/env python
from clusto.scripthelpers import init_script
from clusto.drivers import IPManager
from clusto.drivers import servers
import clusto

from optparse import OptionParser
import sys

def main():
    config, logger = init_script()

    parser = OptionParser(usage="usage: %prog pool-name [pool-name]*")
    parser.add_option("-a", "--attr", dest="attribute", default=False, help="The clusto attribute to retrieve")
    parser.add_option('-d', '--datacenter', dest='datacenter', default=None,
                      help="Datacenter to allocate servers from")
    options, args = parser.parse_args()

    if not args:
        parser.print_help()
        return -1

    pools = []
    for pool in args:
        try:
            obj = clusto.get_by_name(pool)
        except LookupError:
            sys.stderr.write('%s does not exist!\n' % pool)
            return -1
        if obj.type != 'pool':
            sys.stderr.write('%s is not a pool!\n' % obj.name)
            return -1
        pools.append(obj)

    entities = set(pools[0].contents())

    for pool in pools[1:]:
        entities.intersection_update(pool.contents())

    if options.datacenter:
        dc = clusto.get_by_name(options.datacenter)
        dc_hosts = dc.contents(search_children=True, clusto_types=[servers.PenguinServer])
        entities.intersection_update(dc_hosts)

    if options.attribute:
        for entity in entities:
            for attr in entity.attrs(key=options.attribute):
                print str(attr.value)
    else:
        for entity in entities:
            try:
                ip = entity.get_ips()
            except AttributeError, ae:
                ip = None
            if ip:
                print ip[0]
            else:
                print entity.name

if __name__ == '__main__':
    sys.exit(main())
