#!/usr/bin/env python

import sys
import yaml
from optparse import OptionParser

parser = OptionParser(usage="usage: %prog node-name")
(opts, args) = parser.parse_args(sys.argv[1:])
if len(args) != 1:
    parser.error("Incorrect number of arguments!")

import clusto.scripthelpers

config, logger = clusto.scripthelpers.initScript()

from clusto import *

def main():
    entities = clusto.getEntites(attrs=({'key':'fqdn','value':args[0]}))

    if not entities:
        return 1

    clusto_node = entities[0]

    clusto_attrs = clusto_node.attrs(key='puppet', mergeContainerAttrs=True)
    classes = get_puppet_classes(clusto_attrs)
    params = get_puppet_params(clusto_attrs)
    node_info = {'classes': classes, 'parameters': params}

    print yaml.dump(node_info, default_flow_style=False)
    return 0

def get_puppet_classes(attrs):
    return [str(attr.value) for attr in attrs if attr.subkey == 'class']

def get_puppet_params(attrs):
    parameter_attrs = [attr for attr in attrs if attr.subkey != 'class']
    return [{str(attr.subkey): str(attr.value)} for attr in parameter_attrs]

if __name__ == '__main__':
    sys.exit(main())
