#!/usr/bin/env python
"""
Get info about clusto and the clusto database.

"""


import sys

from optparse import OptionParser

import clusto.scripthelpers

cmds = {'driverlist':None,
	'typelist':None}

class Info:
    
    @staticmethod
    def driverlist():
	"Driver List"

	for key in sorted(clusto.driverlist.keys()):
	    print ' ', key
	
    @staticmethod
    def typelist():
	"Type List"
	for key in sorted(clusto.typelist.keys()):
	    print ' ', key

	

def printhelp():
    
    infos = [x for x in dir(Info) if not x.startswith('__')]

    print "Available info commands:"
    
    print '  ', 'all', '\t - ', 'print all info'
    for cmd in infos:
	func = getattr(Info, cmd)
	print '  ', cmd, '\t - ', func.__doc__

    
def main(argv):

    options, args = parseargs(argv)

    config, logger = clusto.scripthelpers.initScript()

    args = args[1:]
    print 
    if not args:
	printhelp()
	return 0

    if 'all' in args:
	args = [x for x in dir(Info) if not x.startswith('__')]
	
	
    for cmd in args:
	if not hasattr(Info, cmd):
	    printhelp()
	    return 0

    for cmd in args:
	if hasattr(Info, cmd):
	    func = getattr(Info, cmd)
	    print func.__doc__, ':'
	    func()
	    print
	    
    return 0

def parseargs(argv):
    
    parser = OptionParser(usage="%prog")

    return parser.parse_args(argv)


if __name__ == '__main__':
    sys.exit(main(sys.argv))
