#!/usr/bin/env python

#import rlcompleter, readline
#readline.parse_and_bind('tab: complete')

import clusto.scripthelpers

config, logger = clusto.scripthelpers.initScript()

from clusto import *

from IPython.Shell import IPShellEmbed
ipshell = IPShellEmbed()
ipshell()
